// ============================================
// mockLickedData.ts - Sample liked data for testing
// ============================================
import { Post } from './types';

export const mockLikedPosts: Post[] = [
  {
    id: '1',
    name: 'Maya Chen',
    username: 'mayacodez',
    timestamp: '2h',
    text: "If you're using AI to replace creativity instead of enhance it, you're missing the entire point of innovation. Tools don’t make art — artists do.",
    likes: 6700,
    isLiked: true,
  },
  {
    id: '2',
    name: 'Ravi Patel',
    username: 'ravithinks',
    timestamp: '5h',
    text: "Electric vehicles aren’t the future if charging infrastructure remains this broken. We solved the horse-to-car transition faster than this.",
    likes: 5200,
    isLiked: true,
  },
  {
    id: '3',
    name: 'Jenna Ortiz',
    username: 'jenortz',
    timestamp: '30m',
    text: "People mocking Gen Z for burnout while working three jobs in an economy designed to crush them is peak irony.",
    likes: 8900,
    isLiked: true,
  },
  {
    id: '4',
    name: 'Tobias Klein',
    username: 'tklein.dev',
    timestamp: '1d',
    text: "AI regulation isn’t about slowing progress. It’s about keeping billion-dollar models from being used like digital nukes with zero accountability.",
    likes: 7600,
    isLiked: true,
  },
  {
    id: '5',
    name: 'Alyssa Ford',
    username: 'alyssaford',
    timestamp: '3h',
    text: "Streaming fatigue is real. I just wanted to watch a movie, not sign six subscriptions and decode which one owns the rights this week.",
    likes: 4300,
    isLiked: true,
  },
  {
    id: '6',
    name: 'Dmitri Vasiliev',
    username: 'dmitritech',
    timestamp: '12h',
    text: "Remote work didn’t kill collaboration — bad managers did. Stop blaming flexible work for poor leadership.",
    likes: 9400,
    isLiked: true,
  },
  {
    id: '7',
    name: 'Layla Brooks',
    username: 'laylabrooks',
    timestamp: '8h',
    text: "It’s wild that climate change denial still exists while half the planet is literally on fire and the other half is underwater.",
    likes: 10100,
    isLiked: true,
  },
  {
    id: '8',
    name: 'Chris J.',
    username: 'chrissaysstuff',
    timestamp: '9m',
    text: "Threads vs X is the most boring rivalry. Both apps forgot that people just want authentic conversations, not algorithmic noise.",
    likes: 3100,
    isLiked: true,
  },
  {
    id: '9',
    name: 'Noor Al-Mansouri',
    username: 'noorwrites',
    timestamp: '7h',
    text: "Tech bros keep calling AI ‘sentient’ because it flatters them to think their code could replace humanity. Relax, it’s still autocomplete with a PR team.",
    likes: 8600,
    isLiked: true,
  },
  {
    id: '10',
    name: 'Leo Grant',
    username: 'leograntmusic',
    timestamp: '2d',
    text: "Music is in its weirdest phase ever. TikTok determines hits, AI remixes old tracks, and real musicians are fighting algorithms for visibility.",
    likes: 5800,
    isLiked: true,
  },
  {
    id: '11',
    name: 'Renee Douglas',
    username: 'reneedouglas',
    timestamp: '10h',
    text: "The U.S. healthcare system charges people more for existing than other countries charge for surgery. That’s not a system — that’s a scam.",
    likes: 9700,
    isLiked: true,
  },
  {
    id: '12',
    name: 'Omar Khan',
    username: 'omark_dev',
    timestamp: '6h',
    text: "Everyone’s building AI tools to summarize content because no one has time to read. Maybe the problem isn’t the content — it’s the overload.",
    likes: 4900,
    isLiked: true,
  },
  {
    id: '13',
    name: 'Tanya Li',
    username: 'tanyatalks',
    timestamp: '15m',
    text: "It’s 2025 and we still don’t teach media literacy in schools. No wonder misinformation spreads faster than facts.",
    likes: 7800,
    isLiked: true,
  },
  {
    id: '14',
    name: 'Marcus Reed',
    username: 'reedmarcus',
    timestamp: '1h',
    text: "NFTs didn’t die — the grifters just rebranded as ‘digital art ecosystems’. Same scam, shinier vocabulary.",
    likes: 6400,
    isLiked: true,
  },
  {
    id: '15',
    name: 'Elena Petrova',
    username: 'elenapetrov',
    timestamp: '4h',
    text: "If billionaires want to go to Mars, fine. But they should pay their taxes on Earth first.",
    likes: 11200,
    isLiked: true,
  },
  {
    id: '16',
    name: 'Kai Johnson',
    username: 'kaijwrites',
    timestamp: '3d',
    text: "AI art isn’t stealing — training on copyrighted work without consent is. There’s a difference, and pretending there isn’t is gaslighting artists.",
    likes: 8800,
    isLiked: true,
  },
  {
    id: '17',
    name: 'Sara Lopez',
    username: 'slopeznews',
    timestamp: '11h',
    text: "Every election year is the ‘most important one yet’ — maybe it’s time we fix the system so democracy doesn’t always feel like a crisis.",
    likes: 7500,
    isLiked: true,
  },
  {
    id: '18',
    name: 'Ethan Blake',
    username: 'blake.eth',
    timestamp: '20m',
    text: "Privacy isn’t paranoia. If your apps know your habits better than your friends do, you’re the product — not the user.",
    likes: 6800,
    isLiked: true,
  },
  {
    id: '19',
    name: 'Zara Kim',
    username: 'zarakim',
    timestamp: '9h',
    text: "We keep calling burnout a personal failure when it’s actually a cultural one. The system rewards exhaustion and calls it ambition.",
    likes: 10300,
    isLiked: true,
  },
  {
    id: '20',
    name: 'Nico Alvarez',
    username: 'nicalv',
    timestamp: '2d',
    text: "You can’t ‘vibe’ your way through climate collapse, AI disruption, and housing crises. At some point, vibes need policy.",
    likes: 8400,
    isLiked: true,
  },
];
