// ============================================
// mockData.ts - Sample data for testing
// ============================================
import { Post } from './types';

export const mockPosts: Post[] = [
  {
    id: '1',
    name: 'Asha Rangappa',
    username: 'asharangappa.b...',
    timestamp: '1h',
    text: 'If the National Guard is really in D.C. to protect federal property, they should probably have been at 1600 Pennsylvania Ave. two days ago',
    likes: 4500,
    isLiked: false,
  },
  {
    id: '2',
    name: 'zay',
    username: 'indigof...',
    timestamp: '15h',
    text: "I don't let myself be ashamed for reading fanfiction because what do you mean I get to be blessed by diverse array of extremely talented authors writing extended stories about my comfort characters and shows for free? Why would I be ashamed of that?",
    likes: 1000,
    isLiked: false,
  },
  {
    id: '3',
    name: 'John Doe',
    username: 'johndoe',
    timestamp: '3h',
    text: 'Just finished building my first React Native app! The learning curve was steep but totally worth it. 🚀',
    likes: 234,
    isLiked: true,
  },
  {
    id: '4',
    name: 'Jane Smith',
    username: 'janesmith',
    timestamp: '5h',
    text: 'Remember: good code is not about being clever, it\'s about being clear and maintainable.',
    likes: 892,
    isLiked: false,
  },
  {
    id: '5',
    name: 'Carlos Mendoza',
    username: 'cmendoza.dev',
    timestamp: '2d',
    text: 'TypeScript saved me from yet another runtime bug today. Bless static typing 🙏',
    likes: 760,
    isLiked: false,
  },
  {
    id: '6',
    name: 'Leila Hassan',
    username: 'leilacodes',
    timestamp: '7h',
    text: 'Can we normalize taking naps as part of the creative process?',
    likes: 1800,
    isLiked: true,
  },
  {
    id: '7',
    name: 'Tomás Rivera',
    username: 'tomasrvr',
    timestamp: '12h',
    text: 'You ever write a function so clean you just sit there smiling at it for a minute?',
    likes: 520,
    isLiked: false,
  },
  {
    id: '8',
    name: 'Emily Carter',
    username: 'emily.codes',
    timestamp: '9m',
    text: 'AI-assisted coding is great but PLEASE still learn the fundamentals. Otherwise you’re just debugging vibes.',
    likes: 2300,
    isLiked: false,
  },
  {
    id: '9',
    name: 'Rahul Patel',
    username: 'rahulpatel',
    timestamp: '3d',
    text: 'Weekend project: building a todo app that automatically deletes tasks you avoid for too long. Productivity by fear. 😂',
    likes: 170,
    isLiked: false,
  },
  {
    id: '10',
    name: 'Sophie Turner',
    username: 'sophiet.dev',
    timestamp: '1h',
    text: 'Finally got dark mode working perfectly across my app. My eyes are thankful 🖤',
    likes: 640,
    isLiked: true,
  },
  {
    id: '11',
    name: 'David Kim',
    username: 'davidk.im',
    timestamp: '22h',
    text: 'The “just one more commit” before bed always turns into 2AM debugging.',
    likes: 410,
    isLiked: false,
  },
  {
    id: '12',
    name: 'Mina Park',
    username: 'minapark',
    timestamp: '4d',
    text: 'Still amazed how CSS can make or break your entire mood for the day.',
    likes: 980,
    isLiked: false,
  },
  {
    id: '13',
    name: 'Jacob Lin',
    username: 'jacoblin',
    timestamp: '11h',
    text: 'When you explain your code and realize your logic doesn’t make sense halfway through...',
    likes: 205,
    isLiked: false,
  },
  {
    id: '14',
    name: 'Fatima Al-Najjar',
    username: 'fatima.codes',
    timestamp: '2d',
    text: 'Documentation is self-care for your future self.',
    likes: 1450,
    isLiked: true,
  },
  {
    id: '15',
    name: 'George Liu',
    username: 'georgeliu',
    timestamp: '8h',
    text: 'Someone please invent a coffee that compiles successfully on the first try.',
    likes: 620,
    isLiked: false,
  },
  {
    id: '16',
    name: 'Olivia Brooks',
    username: 'oliviab',
    timestamp: '30m',
    text: 'Designers: “We need whitespace.” Devs: “We need to fill it.” The eternal conflict.',
    likes: 920,
    isLiked: false,
  },
  {
    id: '17',
    name: 'Ethan Wang',
    username: 'ethan.js',
    timestamp: '14h',
    text: 'My imposter syndrome has version control now. Every commit message: “maybe this works?”',
    likes: 1330,
    isLiked: false,
  },
  {
    id: '18',
    name: 'Riley Johnson',
    username: 'rileyj',
    timestamp: '3d',
    text: 'Shoutout to everyone who refactors code they didn’t write and makes it better.',
    likes: 850,
    isLiked: false,
  },
  {
    id: '19',
    name: 'Chika Okafor',
    username: 'chika.codes',
    timestamp: '6h',
    text: 'Just published my first npm package 🎉 still can’t believe it works!',
    likes: 560,
    isLiked: true,
  },
  {
    id: '20',
    name: 'Marcus Lee',
    username: 'marcuslee.dev',
    timestamp: '1d',
    text: 'Hot take: deleting code is just as productive as writing it.',
    likes: 780,
    isLiked: false,
  },
  {
    id: '21',
    name: 'Priya Sharma',
    username: 'priyasharma',
    timestamp: '10h',
    text: 'Every tech tutorial: “It’s easy!” Me, 3 hours later: crying in terminal.',
    likes: 2500,
    isLiked: false,
  },
  {
    id: '22',
    name: 'Kevin Brown',
    username: 'kevbrown',
    timestamp: '5h',
    text: 'When the linter passes on the first try… that’s a rare dopamine hit.',
    likes: 670,
    isLiked: false,
  },
  {
    id: '23',
    name: 'Nadia Torres',
    username: 'nadiatorres',
    timestamp: '4d',
    text: 'I once changed a font and somehow broke the navbar. CSS is sorcery.',
    likes: 340,
    isLiked: false,
  },
  {
    id: '24',
    name: 'Luke Henderson',
    username: 'lukeh.codes',
    timestamp: '13h',
    text: 'React hooks are fun until you forget one dependency and chaos ensues.',
    likes: 560,
    isLiked: true,
  },
  {
    id: '25',
    name: 'Yasmin Farah',
    username: 'yasminf',
    timestamp: '7h',
    text: 'Day 27 of learning Rust: it’s still fighting me but I respect it.',
    likes: 890,
    isLiked: false,
  },
  {
    id: '26',
    name: 'Liam O’Brien',
    username: 'liamobrien',
    timestamp: '2d',
    text: 'The real skill is writing code that your future self won’t hate.',
    likes: 1030,
    isLiked: false,
  },
  {
    id: '27',
    name: 'Sana Malik',
    username: 'sanamalik',
    timestamp: '4h',
    text: 'Just realized you can use keyboard shortcuts for everything in VSCode. My productivity doubled.',
    likes: 450,
    isLiked: false,
  },
  {
    id: '28',
    name: 'Ben Carter',
    username: 'bencarter',
    timestamp: '9h',
    text: 'Learning Docker was like finally understanding how my dev environment actually works.',
    likes: 310,
    isLiked: false,
  },
  {
    id: '29',
    name: 'Kaito Tanaka',
    username: 'kaitot',
    timestamp: '11h',
    text: 'Minimalism in UI design is not about removing features — it’s about removing confusion.',
    likes: 1420,
    isLiked: true,
  },
  {
    id: '30',
    name: 'Hannah Wright',
    username: 'hannahwrites',
    timestamp: '1d',
    text: 'Working remotely has taught me that snacks are a debugging tool.',
    likes: 940,
    isLiked: false,
  },
  {
    id: '31',
    name: 'Omar Saleh',
    username: 'omarsaleh',
    timestamp: '2h',
    text: 'Every API doc should come with at least one working example. Please.',
    likes: 610,
    isLiked: false,
  },
  {
    id: '32',
    name: 'Talia Green',
    username: 'taliag',
    timestamp: '3h',
    text: 'UI devs be like “It worked in Chrome.” Okay but… why not Safari?',
    likes: 1290,
    isLiked: false,
  },
  {
    id: '33',
    name: 'Jonas Becker',
    username: 'jonasb',
    timestamp: '12h',
    text: 'Open source maintainers deserve medals, therapy, and endless coffee.',
    likes: 3800,
    isLiked: true,
  },
  {
    id: '34',
    name: 'Maya Ortiz',
    username: 'mayaortiz',
    timestamp: '8m',
    text: 'Learning to say “I don’t know yet” is one of the most powerful skills in tech.',
    likes: 970,
    isLiked: false,
  },
  {
    id: '35',
    name: 'Chris Evans',
    username: 'chrisevans.dev',
    timestamp: '9h',
    text: 'Why does every new JS framework make me question my entire life choices?',
    likes: 1570,
    isLiked: false,
  },
  {
    id: '36',
    name: 'Beatrice Ndlovu',
    username: 'bea.ndlovu',
    timestamp: '14h',
    text: 'Just deployed my first full-stack app with CI/CD! The automation feels magical 🪄',
    likes: 880,
    isLiked: true,
  },
  {
    id: '37',
    name: 'Noah Fields',
    username: 'noahfields',
    timestamp: '5d',
    text: 'When your mentor says “good job” — that’s better than any performance review.',
    likes: 1020,
    isLiked: false,
  },
  {
    id: '38',
    name: 'Irene Zhang',
    username: 'irenez',
    timestamp: '2d',
    text: 'Started journaling my coding sessions. Turns out 60% of my time is “what was I doing again?”',
    likes: 540,
    isLiked: false,
  },
  {
    id: '39',
    name: 'Luca Rossi',
    username: 'lucarossi',
    timestamp: '16h',
    text: 'The real senior dev move: knowing when NOT to add a new dependency.',
    likes: 710,
    isLiked: false,
  },
  {
    id: '40',
    name: 'Amira Khan',
    username: 'amirakhan',
    timestamp: '4h',
    text: 'If you’ve ever fixed a bug by accident, congrats — you’re officially a developer.',
    likes: 2700,
    isLiked: true,
  },
];
